<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Pooja-Pathange" failures="1" tests="2" name="Test" time="27.043" errors="0" timestamp="2020-11-15T15:14:54 VET">
  <testcase classname="MAF.Tests.AxiomDemoScenario1" name="AxiomTestScenario1" time="4.795">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.toJsonString(JsonPath.java:1064)
at io.restassured.path.json.JsonPath.prettify(JsonPath.java:685)
at MAF.Tests.AxiomDemoScenario1.getEmployees(AxiomDemoScenario1.java:43)
at MAF.Tests.AxiomDemoScenario1.AxiomTestScenario1(AxiomDemoScenario1.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 34 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- AxiomTestScenario1 -->
  <testcase classname="MAF.Tests.AxiomDemoScenario2" name="AxiomTestScenario2" time="21.751"/>
  <testcase classname="MAF.BasePackage.ProjectBaseClass" name="@BeforeTest Setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest Setup -->
  <testcase classname="MAF.BasePackage.ProjectBaseClass" name="@AfterSuite TearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite TearDown -->
</testsuite> <!-- Test -->
